import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

type FAQ = { q: string; a: string };

const FAQS: FAQ[] = [
  {
    q: "How does auto-scheduling work?",
    a: "The scheduler matches clients to providers using each client's authorization, availability, location preferences, and the provider's qualifications, drive time, and existing caseload. It runs on demand from the Schedule page and proposes sessions for the remainder of the week.",
  },
  {
    q: "What's the difference between a proposed session and a booked session?",
    a: "Proposed sessions are suggestions generated by the scheduler — they show in the schedule but aren't confirmed until approved. The pending count on the Schedule nav badge reflects unapproved proposals for the current week.",
  },
  {
    q: "How do I cancel a session?",
    a: "Click any session block to open the cancel dialog. You can cancel a single session, the rest of the day for one party, or clear the entire week's proposals from the action dock.",
  },
  {
    q: "What is a makeup session?",
    a: "When a billable session is cancelled, the system flags it for makeup. The notifications dropdown in the schedule header lists open makeups and lets you book them with a suggested replacement slot.",
  },
  {
    q: "What is an authorization?",
    a: "Insurance approval for a set number of therapy hours within a date range. Authorizations are required for direct therapy sessions (RBT-delivered) and govern how many hours can be billed per week.",
  },
  {
    q: "Do BCBA sessions need an authorization?",
    a: "No. The active-authorization check applies only to direct therapy. BCBA supervision, assessment, and other non-direct sessions can be booked without an authorization on file.",
  },
  {
    q: "How are drive times calculated?",
    a: "When sessions at different locations are scheduled back-to-back for the same provider, drive time is inserted as a non-billable block using the provider's address and the session locations.",
  },
  {
    q: "How is supervision tracked?",
    a: "Supervision ratios are surfaced in the provider summary on the dashboard. Sessions delivered by a BCBA against an RBT's caseload count toward the supervision requirement.",
  },
  {
    q: "How do I change my timezone?",
    a: "Open the account menu (bottom-left of the sidebar) → Settings. The timezone you pick is display-only and doesn't affect scheduler logic, which always uses the center's timezone for determinism.",
  },
  {
    q: "Where do I report a bug or request a feature?",
    a: "Use the Support link below to reach out. We track all feedback there.",
  },
];

export default async function HelpPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  return (
    <div style={{ maxWidth: 820, margin: "0 auto", padding: "0 4px" }}>
      <h1 style={{ fontSize: 24, fontWeight: 700, color: "var(--ata-gray-900)", margin: 0 }}>
        Help & Resources
      </h1>
      <p style={{ fontSize: 14, color: "var(--ata-gray-600)", marginTop: 6 }}>
        Frequently asked questions, platform policies, and links to legal documentation.
      </p>

      <Section title="Frequently Asked Questions">
        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
          {FAQS.map((item) => (
            <details
              key={item.q}
              style={{
                background: "#FFFFFF",
                border: "1px solid var(--ata-gray-200)",
                borderRadius: 10,
                padding: "10px 14px",
              }}
            >
              <summary style={{ cursor: "pointer", fontWeight: 600, fontSize: 14, color: "var(--ata-gray-900)" }}>
                {item.q}
              </summary>
              <p style={{ marginTop: 8, fontSize: 13, lineHeight: 1.55, color: "var(--ata-gray-700)" }}>
                {item.a}
              </p>
            </details>
          ))}
        </div>
      </Section>

      <Section title="Policies & Legal">
        <ResourceGrid>
          <ResourceCard
            title="Terms of Service"
            description="Acceptable use, account responsibilities, and platform terms."
            href="/legal/terms"
          />
          <ResourceCard
            title="Privacy Policy"
            description="How we collect, store, and protect personal and client data."
            href="/legal/privacy"
          />
          <ResourceCard
            title="HIPAA & Security"
            description="Authentication, access controls, and HIPAA approach. See the Privacy Policy for full details."
            href="/legal/privacy"
          />
          <ResourceCard
            title="Zoom Integration Guide"
            description="How Zoom Chat is used inside the platform and what data we read."
            href="/legal/zoom-guide"
          />
        </ResourceGrid>
      </Section>

      <Section title="Support">
        <ResourceGrid>
          <ResourceCard
            title="Contact Support"
            description="Reach out for help with bugs, billing, or onboarding."
            href="/legal/support"
          />
        </ResourceGrid>
      </Section>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginTop: 28 }}>
      <h2 style={{ fontSize: 16, fontWeight: 700, color: "var(--ata-gray-900)", margin: "0 0 12px" }}>
        {title}
      </h2>
      {children}
    </section>
  );
}

function ResourceGrid({ children }: { children: React.ReactNode }) {
  return (
    <div
      style={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))",
        gap: 12,
      }}
    >
      {children}
    </div>
  );
}

function ResourceCard({ title, description, href }: { title: string; description: string; href: string }) {
  return (
    <Link
      href={href}
      style={{
        display: "block",
        background: "#FFFFFF",
        border: "1px solid var(--ata-gray-200)",
        borderRadius: 12,
        padding: 14,
        textDecoration: "none",
        color: "inherit",
      }}
    >
      <div style={{ fontSize: 14, fontWeight: 700, color: "var(--ata-gray-900)" }}>{title}</div>
      <div style={{ fontSize: 12, color: "var(--ata-gray-600)", marginTop: 4, lineHeight: 1.5 }}>
        {description}
      </div>
    </Link>
  );
}
